#Q1: Is there any difference in the data type of variables list_ and array_list?
Ans: Yes, there is a difference in the data type of list_ and array_list.

list_ is a standard Python list, which is a built-in data structure in Python.
array_list is a NumPy array, which is an object from the NumPy library, and it is specifically designed to handle numerical data efficiently.
The main difference:

A Python list (list_) can hold elements of different types (e.g., integers, strings, etc.), and it doesn't impose any strict type on the data.
A NumPy array (array_list) has a fixed type (dtype), and it is optimized for numerical operations and data manipulation. In this case, since the list contains strings, array_list will have a dtype of str.
## Code to print the data types:



In [1]:
import numpy as np

# List of string elements
list_ = ['1', '2', '3', '4', '5']

# Converting list into a NumPy array
array_list = np.array(object=list_)

# Print the data types of both variables
print("Data type of list_: ", type(list_))
print("Data type of array_list: ", type(array_list))
print("Data type of elements in array_list: ", array_list.dtype)


Data type of list_:  <class 'list'>
Data type of array_list:  <class 'numpy.ndarray'>
Data type of elements in array_list:  <U1


# Q2: Write a code to print the data type of each and every element of both the variables list_ and array_list.
Ans: To print the data type of each element in both the list (list_) and the NumPy array (array_list), we can loop through each element and use the type() function.

## Here’s the code for this:

In [2]:
import numpy as np

# List of string elements
list_ = ['1', '2', '3', '4', '5']

# Converting list into a NumPy array
array_list = np.array(object=list_)

# Print the data type of each element in list_
print("Data types of elements in list_:")
for item in list_:
    print(type(item))

# Print the data type of each element in array_list
print("\nData types of elements in array_list:")
for item in array_list:
    print(type(item))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# Q3: Will there be any difference in the data type of the elements present in both the variables, list_ and array_list, after the following change?
ans: Yes, there will be a difference in the data type of the elements in both variables after you change the dtype of array_list to int.

list_ will still contain string elements ('1', '2', '3', etc.).
array_list will now contain integer elements because you explicitly set dtype=int while creating the NumPy array. This means that the string values will be converted to integers.

# Q4: Write a code to find the following characteristics of variable, num_array:(i) Shape(ii) Size

Code:

In [3]:
import numpy as np

# List of lists
num_list = [[1, 2, 3], [4, 5, 6]]

# Converting the list into a NumPy array
num_array = np.array(object=num_list)

# Finding the shape of num_array
shape = num_array.shape

# Finding the size of num_array
size = num_array.size

# Printing the results
print("Shape of num_array:", shape)
print("Size of num_array:", size)


Shape of num_array: (2, 3)
Size of num_array: 6


#Q5: Write a code to create a NumPy array of a 3x3 matrix containing zeros only, using a NumPy array creation function.

##Code:

In [4]:
import numpy as np

# Creating a 3x3 NumPy array with zeros
zero_matrix = np.zeros((3, 3))

# Printing the resulting array
print(zero_matrix)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Q6: Create an identity matrix of shape (5,5) using NumPy functions.

## Code:

In [5]:
import numpy as np

# Creating a 5x5 identity matrix
identity_matrix = np.eye(5)

# Printing the resulting identity matrix
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
